#!/data/data/com.termux/files/usr/bin/bash

set -euo pipefail

IFS=$'\n\t'

trap ctrl_c 2

 	R='\033[1;31m'        G='\033[1;32m'

        Y='\033[1;33m'

        B='\033[1;34m'

        M='\033[1;35m'

        D='\033[1;36m'

        W='\033[0m'

	clear

	echo -e "$R ____  _                  _"

	echo -e "| __ )(_)_ __   __ _ _ __(_) ___  ___     __  __"

	echo -e "|  _ \| | '_ \ / _  |  __| |/ _ \/ __|____\ \/ /"

	echo -e "| |_) | | | | | (_| | |  | | (_) \__ \_____>  <"

	echo -e "|____/|_|_| |_|\__,_|_|  |_|\___/|___/    /_/\_"

	echo -e "       $B DeadLikado Hack"

	echo

	printf "$Y"

	echo -e "$D   [0] $Y DL.apk            $D [1] $Y binario"

	echo -e "$D   [2] $Y cadena bina..        $D [3] $Y conjela-grupos"

	echo -e "$D   [4] $Y +Nota                $D [5] $Y DeadLikado"

	echo -e "$D   [10] $R Salir $B"

	echo

	echo

	while read -p "Elige Tipo de Binario  >> " SIGN && [ -z $SIGN ]; do

		printf "$R

		[DeadLikado] Porfavor escribe un numero valido

		\n $W"

	done

	if [ $SIGN -eq '1' ]; then

		echo

		printf "$D [Gray]$G Generando DL app$W \n"

		echo

		echo

		cd $PREFIX/bin/modulos

                sleep 3

		cp $PREFIX/bin/modulos/Gray1.jpg /sdcard

		mv /sdcard/Gray1.jpg /sdcard/viruz.apk

		echo

		printf "$G \n \t Listoo Ahora esta en tu memoria interna!!"

		echo

		printf "$D presiona en $G enter $D para continuar"

		echo

		read enter

		binarios

		

	elif [ $SIGN -eq '2' ]; then

		printf "$D [Gray]$G Creando binario $Y \n"

		echo

		echo

		cd $PREFIX/bin//modulos

		sleep 3

		cat $PREFIX/bin/modulos/Gray2.jpg

		echo

		printf "$G \n \t Listo!!"

		echo

		printf "$D Presiona en $G enter $D para continuar"

		echo

		read enter

		binarios

		

	elif [ $SIGN -eq '3' ]; then

		printf "$D [Gray] $G Creando cadena-bina..$Y \\n"

		echo

		echo

		cd $PREFIX/bin/modulos

		sleep 3

		cat $PREFIX/bin/modulos/Gray3.jpg

		echo

		printf "$G \n \t Listo!!"

		echo

		printf "$D presiona en $G enter $D para continuar"

		echo

		read enter

		binarios

		

	elif [ $SIGN -eq '4' ]; then

		printf "$D generando un conjelador $Y \\n"

		echo

		echo

		cd $PREFIX/bin/modulos

		sleep 5

		cat $PREFIX/bin/modulos/dead.jpg

		echo

		printf "$G \n \t Listo!!"

		echo

		printf "$D presiona en $G enter $D para regresar"

		echo

		read enter

		binarios

	

	

	elif [ $SIGN -eq '5' ]; then

		printf "$D Estrayendo Nota $Y \\n"

		echo

		echo

		cd $PREFIX/bin/modulos

		sleep 2

		bash $PREFIX/bin/modulos/Gray10.jpg

		echo

		printf "$G \n \t Listoo!!"

		echo

		printf "$D presiona en $G enter $D para regresar"

		echo

		read enter

		binarios

	

	elif [ $SIGN -eq '6' ]; then

		printf "$D Please wait DeadLikado Contact  \\n"

		echo

		echo

		cd $PREFIX/bin/modulos

		sleep 5

		bash $PREFIX/bin/modulos/Grayy.jpg

		echo

		printf "$G \n \t Listoo!!"

		echo

		printf "$D presiona en $G enter $D para continuar"

		read enter

		echo

		binarios

	elif [ $SIGN -eq '10' ]; then

	        echo

		echo

		printf "$D DeadLikado Hack\\n"

		echo

		echo

	else

	       bash $PREFIX/bin/binarios

       fi
